---
title: "Pseudocodes"
author: "Richard"
date: "8/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Power analysis for TS bands
\textbf{Goal}: To compute a list of $K$ powers for the TS test which each power is computed from $M$ test samples with sample size of $n$.  
\textbf{Input}: 
\begin{itemize} 
\item $K = \text{number of powers to compute}$ 
\item $M = \text{number of test samples to compute a single power}$
\item $n = \text{sample size of each test sample}$
\item $N = \text{number of independent normal sample to simulate a TS band}$ 
\item $\alpha = \text{type I error}$
\end{itemize}
\textbf{Initialization}: A zero list of K elements (powers): $\text{powers}=(0,...,0)$  
\textbf{Algorithm}:
\begin{enumerate}
\item Simulate a standardized TS band $(L_1,U_1),...,(L_n,U_n)$ with the given $N$ and $\alpha$ (See the algorithm in the paper by Aldor-Noiman et al.)
\item \textbf{for} $k=1,...,K$:
  \begin{enumerate}
    \item[] \textbf{for} $m=1,...,M$:
    \begin{itemize}
      \item Draw a test sample $X_1,...,X_n$. Standardize the sample $Z_i=\frac{X_i-\hat{\mu}}{\hat{\sigma}}$.
      \item \textbf{if} $L_i \leq Z_i \leq U_i$ for all $i=1,...,n$: \\
      $\text{powers}[k] = \text{powers}[k]$ \\
      \textbf{else}: \\
      $\text{powers}[k] = \text{powers}[k] + 1/M$
    \end{itemize}
  \end{enumerate}
\item \textbf{return} powers  
\end{enumerate}

\newpage


## Power analysis for Monte Carlo Procedure
\textbf{Goal:} To compute a list of $K$ powers for the Monte Carlo test which each power is computed from $M$ test samples with sample size of $n$.  
\textbf{Input}: 
\begin{itemize} 
\item $K = \text{number of powers to compute}$ 
\item $M = \text{number of test samples to compute a single power}$
\item $n = \text{sample size of each test sample}$
\item $N = \text{number of simulated Monte Carlo statistics from independent normal sample}$ 
\item $\alpha = \text{type I error}$
\end{itemize}
\textbf{Initialization}: A zero list of K elements (powers): $\text{powers}=(0,...,0)$  
\textbf{Algorithm}:
\begin{enumerate}
\item Simulate a list of $N$ Monte Carlo statistics $S^{(1)},...,S^{(N)}$ by $N$ independent samples, each of size $n$, from a standard normal distribution. (See the algorithm in the paper by Hazelton)
\item \textbf{for} $k=1,...,K$:
  \begin{enumerate}
    \item[] \textbf{for} $m=1,...,M$:
    \begin{itemize}
      \item Draw a test sample $X_1,...,X_n$. Standardize the sample $Z_i=\frac{X_i-\hat{\mu}}{\hat{\sigma}}$.
      \item Compute the observed Monte Carlo statistics $s_{obs}$ for $Z_1,...,Z_n$. 
      \item Calculate the Monte Carlo $p$ value, $P=\#(S^{(j)}\geq s_{obs})/N, j=1,...,N$.
      \item \textbf{if} $P > \alpha$: \\
      $\text{powers}[k] = \text{powers}[k]$ \\
      \textbf{else}: \\
      $\text{powers}[k] = \text{powers}[k] + 1/M$
    \end{itemize}
  \end{enumerate}
\item \textbf{return} powers  
\end{enumerate}

